# Generated by Django 6.1 on 2026-08-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('database', 'Bases de données'), ('data_ai', 'Data Science & Intelligence Artificielle'), ('development', 'Développement logiciel'), ('systems', 'Systèmes & outils'), ('fundamentals', 'Fondamentaux informatiques')], max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
    ]
