# Generated by Django 6.1 on 2026-08-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='type',
            field=models.CharField(choices=[('degree', 'Diplôme'), ('certificate', 'Certificat')], default='degree', max_length=20),
        ),
    ]
