# Generated by Django 6.1 on 2026-08-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_education_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('native', 'Natif'), ('fluent', 'Courant'), ('operational', 'Opérationnel'), ('intermediate', 'Intermédiaire'), ('basic', 'Notions')], max_length=20)),
            ],
        ),
    ]
