# Generated by Django 6.1 on 2026-08-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='career_summary',
        ),
        migrations.RemoveField(
            model_name='about',
            name='current_focus',
        ),
        migrations.RemoveField(
            model_name='about',
            name='education_summary',
        ),
        migrations.RemoveField(
            model_name='about',
            name='professional_goals',
        ),
    ]
